package main

import (
	"device-go/packages/aliver"
	"device-go/packages/api"
	"device-go/packages/config"
	"device-go/packages/crypto"
	"device-go/packages/events"
	"device-go/packages/handlers"
	"device-go/packages/registration"
	"device-go/packages/storage"
	"device-go/packages/utils"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"runtime"
	"strings"
	"syscall"
	"time"

	"github.com/coalalib/coalago"
	log "github.com/ndmsystems/golog"
	"github.com/spf13/cobra"
)

const serviceName = "iot4bd"

var env string  // environment (config name)
var port string // coala port

func main() {
	var rootCmd = &cobra.Command{
		Use:   "device",
		Short: "Device CLI",
		Run:   runDevice,
	}
	rootCmd.PersistentFlags().StringVar(&env, "env", "prod", "Set environment")
	rootCmd.PersistentFlags().StringVar(&port, "port", "5684", "Set coala port")
	rootCmd.ParseFlags(os.Args[1:])

	config.Init(env)
	log.Init(config.Bool("debug"))

	initCmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize the device",
		Run:   deviceInit,
	}

	statusCmd := &cobra.Command{
		Use:   "status",
		Short: "Show device status",
		Run:   deviceStatus,
	}

	rootCmd.AddCommand(initCmd)
	rootCmd.AddCommand(statusCmd)
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

func runDevice(_ *cobra.Command, _ []string) {
	crypto.Init(config.Get("localFiles.keys"))

	if utils.FileExists(config.Get("localFiles.init")) {
		// generate storage file with the init file data
		log.Info("Init Local Storage")
		storage.Init(
			config.Get("localFiles.contract"),
			config.Get("localFiles.init"),
			config.Get("everscale.elector"),
			config.Get("everscale.vendor"),
			config.Get("everscale.deviceAPI"),
			config.Get("info.type"),
			config.Get("info.version"))
	} else {
		// wait for storage file to be generated by the init command
		storage.WaitForData()
	}

	// сервер для запросов от клиентов и нод
	server := coalago.NewServer()
	server.GET("/info", handlers.GetInfo)
	server.POST("/cmd", handlers.ExecCmd)
	server.POST("/update", handlers.Update)
	server.POST("/sign", handlers.Sign)

	go listen(server)
	go sigterm()

	for {
		start := storage.Device.NodeIpPort == ""
		// регистрируем устройство на ноде
		// если ошибка, то повторяем цикл регистрации
		err := registration.Register()
		if err == nil {
			go sendEvents(start)

			// начинаем слать alive пакеты, чтобы сохранять соединение для udp punching
			aliver.Run(server, config.Time("timeout.alive"))
		} else {
			log.Error(err)
			time.Sleep(5 * time.Second)
		}
	}
}

func listen(server *coalago.Server) {
	if err := server.Listen(":" + port); err != nil {
		log.Fatal(err)
	}
}

func sigterm() {
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	<-c
	os.Exit(0)
}

func sendEvents(start bool) {
	if storage.Device.Events {
		if start {
			events.Send(new(events.Start))
		}
		events.Send(new(events.Register))
	}
}

func deviceInit(_ *cobra.Command, _ []string) {
	fmt.Println("Init Device")
	storage.Init(
		config.Get("localFiles.contract"),
		config.Get("localFiles.init"),
		config.Get("everscale.elector"),
		config.Get("everscale.vendor"),
		config.Get("everscale.deviceAPI"),
		config.Get("info.type"),
		config.Get("info.version"))
	if storage.Device.Address != "" {
		fmt.Println("Device contract is already deployed. Address:")
		fmt.Println(storage.Device.Address)
		return
	}
	if !isServiceRunning() {
		fmt.Printf("%s service is not running.\n", serviceName)
		fmt.Printf("to start it run the following command in a separate terminal:\n")
		if runtime.GOOS == "darwin" {
			fmt.Printf("brew services start %s\n", serviceName)
		} else if runtime.GOOS == "linux" {
			fmt.Printf("systemctl start %s\n", serviceName)
		}

		for {
			time.Sleep(time.Second)
			if isServiceRunning() {
				break
			}
		}
	}

	fmt.Println("Waiting for contract deployment...")
	for {
		storage.Update()
		if storage.Device.Address != "" {
			fmt.Println("Device contract is deployed.")
			fmt.Printf("Address: %s\n", storage.Device.Address)
			fmt.Printf("Group:   %s\n", storage.Device.Group)
			fmt.Printf("Elector: %s\n", storage.Device.Elector)
			return
		}
		time.Sleep(time.Second)
	}
}

func isServiceRunning() bool {
	out, err := exec.Command("pgrep", "-x", serviceName).Output()
	if err != nil {
		return false
	}
	return strings.TrimSpace(string(out)) != ""
}

func deviceStatus(_ *cobra.Command, _ []string) {
	storage.Init(
		config.Get("localFiles.contract"),
		config.Get("localFiles.init"),
		config.Get("everscale.elector"),
		config.Get("everscale.vendor"),
		config.Get("everscale.deviceAPI"),
		config.Get("info.type"),
		config.Get("info.version"))
	fmt.Print("Status:  ")
	input := map[string]string{"address": string(storage.Device.Address)}
	_, err := api.GET("device/info", input)
	if err != nil {
		fmt.Println("Offline")
	} else {
		fmt.Println("Online")
	}
	fmt.Printf("Name:    %s\n", storage.Device.Name)
	fmt.Printf("Address: %s\n", storage.Device.Address)
	fmt.Printf("Node:    %s\n", storage.Device.Node)
	fmt.Printf("Group:   %s\n", storage.Device.Group)
	fmt.Printf("Elector: %s\n", storage.Device.Elector)
	balance := api.GetBalance()
	fmt.Printf("Balance: %.9f EVER\n", balance)
}
