#!/bin/sh

LOG_FILE="/opt/var/log/iot4b.log"
SERVICE_FILE="/etc/init.d/iot4b"

if [ -x "$SERVICE_FILE" ]; then
    "$SERVICE_FILE" stop
    "$SERVICE_FILE" disable
    rm "$SERVICE_FILE"
fi

rm -rf /opt/iot4b

rm -f  LOG_FILE

echo "IOT4B deleted"

