#!/bin/sh

device_name=$(uname -n)
echo "Device name: $device_name"

# Функция для ввода значения с проверкой на пустоту
get_input() {
    local value=""
    while true; do
        read value
        if [ -z "$value" ]; then
            echo "Empty value is not allowed. Try again."
        elif [[ "$value" == "q" || "$value" == "exit" ]]; then
            echo "Exiting input."
            exit 1
        else
            echo "$value"
            return
        fi
    done
}
# Запрос адреса группы
echo -e "\n\n--------------------------------------------------------------"
echo "Enter the blockchain address of Device Group:"
group_address=$(get_input)

# Запрос публичного ключа владельца
echo -e "\n\n--------------------------------------------------------------"
echo "Enter the owner's public key (starting with 0x):"
owner_key=$(get_input)

# Замена макросов в конфигурационном файле
config_file="/opt/iot4b/init.json"
sed -i "s|__GROUP__|$group_address|g" $config_file
sed -i "s|__OWNER__|$owner_key|g" $config_file
sed -i "s|__DEVICENAME__|$device_name|g" $config_file

# Запуск сервиса
service_file="/etc/init.d/iot4b"
if [ -x $service_file ]; then
    $service_file start    
    $service_file enable   
else
    echo "Service script $service_file not found or not executable."
fi


FILE="/opt/iot4b/contract.json"
TIMEOUT=60          # Секунды ожидания

echo ""
echo ""
echo "Waiting for smartcontract deployment..."

i=0
while [ $i -lt $TIMEOUT ]; do
    if [ -f "$FILE" ]; then
        # Парсим значение address (если нет jq)
        ADDRESS=$(grep -m1 '"address"' "$FILE" | sed -E 's/.*"address":[[:space:]]*"([^"]+)".*/\1/')
        if [ -n "$ADDRESS" ] && [ "$ADDRESS" != "" ]; then
            echo -e "\n\n--------------------------------------------------------------"
            echo "$device_name address: $ADDRESS"
            echo "Use this address for adding this device to the app"
            echo -e "\n\n\n\n"
            exit 0
        fi
    fi
    i=$((i + 1))
    sleep 1
done

echo "Timeout reached. Smartcontract for $device_name not deployed."
exit 1
