#!/bin/sh

SERVICE="iot4b"
SERVICE_FILE="/etc/init.d/$SERVICE"

if [ -x "$SERVICE_FILE" ]; then
    echo "Stopping $SERVICE service..."
    "$SERVICE_FILE" stop
    killall $SERVICE
    echo "Service $SERVICE stopped"
    rm "$SERVICE_FILE"
fi

rm -rf /opt/$SERVICE
rm -f  /opt/var/log/$SERVICE.log
echo "$SERVICE removed"

