monit:
  hosts:
    devices:
      ansible_host: 64.23.153.200

  ##################################################
  vars:
    service: device
    config: dev
    PROJECTPATH: ../../
    DEPLOYROOT: /opt/everiot
    BuildBin: device_bin
    monit_alert: mobile@.com # адрес для монита
    ansible_ssh_user: root
    GOOS: linux
    GOARCH: amd64
    CGO: 1