#!/bin/sh
START=50
STOP=50

SERVICE_NAME="iot4b"
LOG_FILE="/var/log/$SERVICE_NAME.log"

start() {
    echo "Starting $SERVICE_NAME..."
    if pgrep $SERVICE_NAME > /dev/null; then
        echo "$SERVICE_NAME is already running!"
        exit 1
    fi
    cd /opt/$SERVICE_NAME && ./$SERVICE_NAME -env=iot4b > $LOG_FILE 2>&1 &
    echo "Service $SERVICE_NAME started"
}

stop() {
    echo "Stopping $SERVICE_NAME..."
    killall $SERVICE_NAME
    echo "Service $SERVICE_NAME stopped"
}

restart() {
    stop
    start
}

status() {
    if pgrep $SERVICE_NAME > /dev/null; then
        echo "Service $SERVICE_NAME is running"
    else
        echo "Service $SERVICE_NAME is not running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
