version: 0.1mac
type: test-device
vendor: apple

debug: true

keysFile: "device.keys.json"

device:
  contractFile: "device.contract"

coapServerPort: :5683
nodeHost: 157.245.57.218:5683
nodes:
  0: 157.245.57.218:5683
  1: 157.245.57.218:5683
  2: 157.245.57.218:5683
aliveInterval: 2s
