version: 0.1mac
type: test-device
vendor: apple

debug: true

keysFile: "device.keys.json"

device:
  contractFile: "device.contract"

coapServerPort: :5683
nodeHost: 157.245.57.218:5683
masterNodes:
  - 157.245.57.218
  - 188.166.71.64
  - 192.81.216.57

aliveInterval: 2s
