
debug: true
env: dev

info:
  version: "0.0.3"
  type: "Keenetic device"

localFiles:
  keys: "device.keys.json"
  contract: "device.contract.dev.json"
  init: "device.init.json"

timeout:
  alive: 10s #alive interval
  coala: 3m  # timeout for coala reguests
  registerRepeat: 1h #period for registration repeat

masterNodes:
  - 157.245.57.218:5683
  - 188.166.71.64:5683
  - 192.81.216.57:5683

everscale:
  elector: "0:20a9657c902ad65dd6eb08b4eb7ec4d3f45bebda5d763bbd7b0b3826824a216a"
  vendor:
    address: "0:9da539518766ebbb30541d460d15c1036c004053b9d4cb9b3b24ce6b058dad12"
    name: "Keenetic"
    data: ""