---

- 
  name: "Distribute files"
  hosts: all
  serial: 20 # сколько серваков обновляем в потоке. 1 - это по одному, все таски по очереди.
  gather_facts: False
  vars: 
    SERVICEBIN: "{{service}}-{{config}}"
    CONFIG: "{{config}}"
    DEPLOYPATH: "{{DEPLOYROOT}}/{{service}}"
  tasks:
    - name: Add hosts dynamically
      add_host:
        name: "{{ 'device' ~ item }}"
        ansible_host: 64.23.153.200
        port: "{{ 6000 + start + item }}"
        groups: test
      loop: "{{ range(count)|list }}"
      vars:
        start: 1
        count: 200 
    - include_tasks: tasks/build_golang.yml
    - include_tasks: tasks/sync_files.yml


- name: "restart monit for all services"
  hosts: monit
  serial: 1 # сколько серваков обновляем в потоке. 1 - это по одному, все таски по очереди.
  gather_facts: False
  vars: 
    SERVICEBIN: "{{service}}-{{config}}"
    CONFIG: "{{config}}"
    DEPLOYPATH: "{{DEPLOYROOT}}/{{service}}"

  tasks:
    - include_tasks: tasks/restart_service.yml