---
- name: "Distribute files and restart service"
  hosts: test
  serial: 10 # сколько серваков обновляем в потоке. 1 - это по одному, все таски по очереди.
  gather_facts: False
  vars: 
    SERVICEBIN: "{{service}}-{{config}}"
    CONFIG: "{{config}}"
    DEPLOYPATH: "{{DEPLOYROOT}}/{{service}}"

  tasks:
    - include_tasks: tasks/build_golang.yml
    - include_tasks: tasks/sync_files.yml
    - include_tasks: tasks/restart_service.yml