#!/bin/sh

device_name="IOT4B device"

if [ -f /etc/openwrt_release ]; then
    echo "Detected OpenWRT."
    device_name=$(uname -n)
elif grep -qi "NDMS" /proc/version; then
    echo "Detected Keenetic. Installing dependencies..."
    ##opkg install libndm ndmq
    device_name=$(uname -n)
fi

echo "Device name: $device_name"

# Функция для ввода значения с проверкой на пустоту
get_input() {
    local value=""
    while true; do
        read value
        if [ -z "$value" ]; then
            echo "Empty value is not allowed. Try again."
        elif [[ "$value" == "q" || "$value" == "exit" ]]; then
            echo "Exiting input."
            exit 1
        else
            echo "$value"
            return
        fi
    done
}
# Запрос адреса группы
echo "Enter the blockchain address of Device Group:"
group_address=$(get_input)

# Запрос публичного ключа владельца
echo "Enter the owner's public key:"
owner_key=$(get_input)

# Замена макросов в конфигурационном файле
config_file="/opt/iot4b/init.json"
sed -i "s|__GROUP__|$group_address|g" $config_file
sed -i "s|__OWNER__|$owner_key|g" $config_file
sed -i "s|__DEVICENAME__|$device_name|g" $config_file

# Запуск сервиса
if [ -x /opt/etc/init.d/iot4b ]; then
    /opt/etc/init.d/iot4b enable   # Включить автозапуск
    /opt/etc/init.d/iot4b start    # Запустить сервис
    echo "Service iot4b started and enabled on boot."
else
    echo "Service script /opt/etc/init.d/iot4b not found or not executable."
fi