- name: Copy config files
  copy:
    src: "{{PROJECTPATH}}config/{{config}}.yml"
    dest: "{{DEPLOYPATH}}-{{port}}/config/"

- name: Copy compiled binary
  copy:
    src={{PROJECTPATH}}{{BuildBin}}
    dest={{DEPLOYPATH}}-{{port}}/{{SERVICEBIN}}-{{port}}
    mode=0744

- name: Deliver monit scripts
  template:
    src={{PROJECTPATH}}/ansible/templates/monit_conf.j2
    dest=/etc/monit/conf.d/tc_{{SERVICEBIN}}-{{port}}
    mode=0644
  vars:
    port: "{{port}}"