
- name: Copy compiled binary {{PROJECTPATH}}{{BuildBin}} to {{DEPLOYPATH}}-{{item}}/{{SERVICEBIN}}-{{item}}
  copy:
    src={{PROJECTPATH}}{{BuildBin}}
    dest={{DEPLOYPATH}}-{{item}}/{{SERVICEBIN}}-{{item}}
    mode=0744
  loop: "{{ range(port_start, port_end)|list }}"

- name: Sync configs file {{PROJECTPATH}}config/ to {{DEPLOYPATH}}-{{item}}/config
  ansible.posix.synchronize:
    src={{PROJECTPATH}}config/
    dest={{DEPLOYPATH}}-{{item}}/config
    delete=yes
  loop: "{{ range(port_start, port_end)|list }}"

- name: Deliver monit script for {{SERVICEBIN}}-{{item}}
  template:
    src={{PROJECTPATH}}/ansible/templates/monit_conf.j2
    dest=/etc/monit/conf.d/tc_{{SERVICEBIN}}-{{item}}
    mode=0644
    delete=yes
  vars:
    port: "{{item}}"
  loop: "{{ range(port_start, port_end)|list }}"