
- name: Copy compiled binary {{PROJECTPATH}}{{BuildBin}} to {{DEPLOYPATH}}/{{SERVICEBIN}}
  copy:
    src={{PROJECTPATH}}{{BuildBin}}
    dest={{DEPLOYPATH}}/{{SERVICEBIN}}
    mode=0744

- name: Sync configs file {{PROJECTPATH}}config/ to {{DEPLOYPATH}}/config
  ansible.posix.synchronize:
    src={{PROJECTPATH}}config/
    dest={{DEPLOYPATH}}/config
    delete=yes

- name: Sync assets file {{PROJECTPATH}}contracts/ to {{DEPLOYPATH}}/contracts
  ansible.posix.synchronize:
    src={{PROJECTPATH}}contracts/
    dest={{DEPLOYPATH}}/contracts
    delete=yes

- name: Deliver monit script for {{SERVICEBIN}}
  template:
    src={{PROJECTPATH}}/ansible/templates/monit_conf.j2
    dest=/etc/monit/conf.d/tc_{{SERVICEBIN}}
    mode=0644

