#!/bin/sh

START=50
STOP=50

SERVICE_NAME="iot4b"
SERVICE_FILE="/etc/init.d/$SERVICE_NAME"
LOG_FILE="/var/log/$SERVICE_NAME.log"

start_service() {
    echo "Starting $SERVICE_NAME..."
    if pgrep "$SERVICE_NAME" > /dev/null; then
        echo "$SERVICE_NAME is already running!"
        exit 1
    fi
    cd /opt/"$SERVICE_NAME" && ./"$SERVICE_NAME" --env iot4b > "$LOG_FILE" 2>&1 &
    echo "Service $SERVICE_NAME started"
}

stop_service() {
    echo "Stopping $SERVICE_NAME..."
    killall "$SERVICE_NAME" 2>/dev/null
    echo "Service $SERVICE_NAME stopped"
}

restart_service() {
    stop_service
    start_service
}

status_service() {
    if pgrep "$SERVICE_NAME" > /dev/null; then
        echo "Service $SERVICE_NAME is running"
    else
        echo "Service $SERVICE_NAME is not running"
    fi
}

enable_service() {
    echo "Enabling $SERVICE_NAME service to start on boot..."
    ln -sf "$SERVICE_FILE" "/etc/rc.d/S${START}${SERVICE_NAME}"
    ln -sf "$SERVICE_FILE" "/etc/rc.d/K${STOP}${SERVICE_NAME}"
    echo "$SERVICE_NAME service enabled."
}

disable_service() {
    echo "Disabling $SERVICE_NAME service from starting on boot..."
    rm -f "/etc/rc.d/S${START}${SERVICE_NAME}"
    rm -f "/etc/rc.d/K${STOP}${SERVICE_NAME}"
    echo "$SERVICE_NAME service disabled."
}

case "$1" in
    start)
        start_service
        ;;
    stop)
        stop_service
        ;;
    restart)
        restart_service
        ;;
    status)
        status_service
        ;;
    enable)
        enable_service
        ;;
    disable)
        disable_service
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|enable|disable}"
        exit 1
        ;;
esac

exit 0