# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

#  deploy-dev:
#    runs-on: self-hosted
#    env:
#      HOME: "/root"
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Set up Go
#      uses: actions/setup-go@v4
#      with:
#        go-version: '1.21'
#
#    - name: Run Ansible playbook at ./ansible/playbooks/deploy_dev.yml
#      uses: dawidd6/action-ansible-playbook@v2
#      with:
#        playbook: deploy_dev.yml
#        directory: ./ansible/playbooks
#        options: |
#          -i ../inventory/dev.yml
#
#
#    - name: Run Ansible playbook at ./ansible/playbooks/deploy_test.yml
#      uses: dawidd6/action-ansible-playbook@v2
#      with:
#        playbook: deploy_test.yml
#        directory: ./ansible/playbooks
#        options: |
#          -i ../inventory/test.yml

  deploy-prod:
    runs-on: self-hosted
    env:
      HOME: "/root"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

     # - name: Run Ansible playbook at ./ansible/playbooks/deploy_prod.yml
     #   uses: dawidd6/action-ansible-playbook@v2
     #   with:
     #     playbook: deploy_prod.yml
     #     directory: ./ansible/playbooks
     #     options: |
     #       -i ../inventory/prod.yml

      - name: Run Ansible playbook at ./ansible/playbooks/deploy_test.yml
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy_test.yml
          directory: ./ansible/playbooks
          options: |
            -i ../inventory/test.yml