# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-device-1:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run Ansible playbook at ./ansible/playbooks/deploy_dev.yml
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy_dev.yml
        directory: ./ansible/playbooks
        options: |
          -i ../inventory/dev.yml --extra-vars "service=device-1 port=5684"

  build-device-2:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run Ansible playbook at ./ansible/playbooks/deploy_dev.yml
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy_dev.yml
        directory: ./ansible/playbooks
        options: |
          -i ../inventory/dev.yml --extra-vars "service=device-2 port=5685"

  build-device-3:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run Ansible playbook at ./ansible/playbooks/deploy_dev.yml
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy_dev.yml
        directory: ./ansible/playbooks
        options: |
          -i ../inventory/dev.yml --extra-vars "service=device-3 port=5686"