#!/bin/sh

SERVICE="iot4b"
SERVICE_FILE="/opt/etc/init.d/S50$SERVICE"

if [ -x "$SERVICE_FILE" ]; then
    echo "Stopping $SERVICE service..."
    "$SERVICE_FILE" stop
    "$SERVICE_FILE" disable
    killall "$SERVICE"
    rm "$SERVICE_FILE"
    echo "Service $SERVICE removed"
fi

rm -rf "/opt/$SERVICE"
rm -f  "/opt/var/log/$SERVICE.log"
echo "$SERVICE removed"

