#!/bin/sh

SERVICE="iot4b"
SERVICE_FILE="/etc/init.d/S50iot4b"

if [ -x "$SERVICE_FILE" ]; then
    echo "Stopping iot4b service..."
    "$SERVICE_FILE" stop
    "$SERVICE_FILE" status
    killall "$SERVICE"
    rm "$SERVICE_FILE"
    echo "Service iot4b removed"
fi

rm -rf /opt/iot4b
rm -f  /opt/var/log/iot4b.log
echo "IOT4B removed"

